services:
  db:
    image: pgvector/pgvector:pg15
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: beuntethered_local
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
