ALTER TYPE "EvidenceSourceType" ADD VALUE IF NOT EXISTS 'NETLIFY';
ALTER TYPE "EvidenceSourceType" ADD VALUE IF NOT EXISTS 'CLOUDFLARE';
ALTER TYPE "EvidenceSourceType" ADD VALUE IF NOT EXISTS 'RENDER';
ALTER TYPE "EvidenceSourceType" ADD VALUE IF NOT EXISTS 'FLY';
ALTER TYPE "EvidenceSourceType" ADD VALUE IF NOT EXISTS 'DIGITALOCEAN';
ALTER TYPE "EvidenceSourceType" ADD VALUE IF NOT EXISTS 'HEROKU';
