-- Baseline migration: live Supabase DB state as of 2026-04-12
CREATE EXTENSION IF NOT EXISTS pg_graphql;
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS supabase_vault;
CREATE EXTENSION IF NOT EXISTS uuid_ossp;
CREATE EXTENSION IF NOT EXISTS vector;
CREATE TYPE "Role" AS ENUM ('CLIENT', 'FACILITATOR');
CREATE TYPE "ProjectStatus" AS ENUM ('OPEN', 'ACTIVE', 'COMPLETED', 'DISPUTED', 'CANCELLED');
CREATE TYPE "BillingType" AS ENUM ('FIXED_PRICE', 'HOURLY_RETAINER', 'HOURLY_NO_RETAINER');
CREATE TYPE "MilestoneStatus" AS ENUM ('PENDING', 'FUNDED_IN_ESCROW', 'SUBMITTED_FOR_REVIEW', 'APPROVED_AND_PAID', 'DISPUTED');
CREATE TYPE "TimeEntryStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'INVOICED');
CREATE TYPE "BidStatus" AS ENUM ('OPEN', 'ACCEPTED', 'REJECTED', 'WITHDRAWN');
CREATE TYPE "ChangeOrderStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
CREATE TYPE "PlatformTier" AS ENUM ('STANDARD', 'PRO', 'ELITE');
CREATE TYPE "SubscriptionTier" AS ENUM ('FREE', 'BYOC_PRO');
